---
title: "Assignment_2"
format: html
editor: visual
---

**Assignment - 2:  Scraping an html table from a web page**

<https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132>

```{r}
rm (list = ls())
library(tidyverse)
library(rvest) 
library(janitor) 
library(lubridate)
library(dplyr)
```

```{r}
url <- "https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132"


motor <- read_html(url)


df_motor <- url %>% 
  read_html() %>% 
  html_element("table") %>% 
  html_table() %>% 
  row_to_names(row_number = 1)


df_motor <- df_motor %>% 
  separate(`WLTP-tall`, into=c("wltp_km", "wltp_kwh"), sep="/") %>% 
  separate(wltp_km, into="wltp_km", sep=" ") %>% 
  separate("STOPP", into=c("stopp_km"), sep=" ")
  
df_motor <- df_motor %>% 
  na_if("x") %>% 
  drop_na()


df_motor <- df_motor %>% 
  mutate_at(c('wltp_km', 'stopp_km'), as.numeric)


df_motor %>% 
  ggplot(aes(x=wltp_km, y=stopp_km))+
  geom_point()+
  geom_abline(slope=1, color="red")
```
